var Organo=require('./organo');
var Canal=require('./canal')
var assert=require('assert');

function Punto(parametros){
	// parametros {canal, numero, nombre, chinoTradicional}
	this.canal=parametros.canal;
	this.numero=parametros.numero;
	this.nombre=parametros.nombre;
	this.chinoTradicional=parametros.chinoTradicional;
	this.nombreTradicional=parametros.nombreTradicional;
	
	this.getCanal=function(){
		return this.canal;
	}
	
	this.getNumero=function(){
		return this.numero;
	}
	
	this.getNombre=function(){
		return this.nombre;
	}
	
	this.getNombreTradicional=function(){
		return this.nombreTradicional;
	}
	
	this.getChinoTradicional=function(){
		return this.chinoTradicional;
	}
}

function puntoPorCanalNumero(can, num){
	// canal es el objeto canal (nombre_pieMano, o  dumai o renmai)
// canalNumeroPuntoMap.set({canal: Canal.TAIYIN , numero: 1}, SP_1 ); -> estructura de mi map de puntos
// myMap.get(keyObj); -> asi se obtiene el valor dada una clave compuesta
	var keyObj = {
		canal: can,
		numero: num
	}
	return(canalNumeroPuntoMap.get(JSON.stringify(keyObj)));
}

function puntoPorNombre(nombre){
	var	parametros={ 
		canal: Canal.TAIYIN_MANO,
		numero: 1,
		nombre: 'No me lo se'
	};  
	
	var p=new Punto.Punto(parametros);
	
	switch(nombre) {
		case 'd ': return(p); break;
		default: return(p);
	}
}

// Todos los puntos sacados de Deadman / wikipedia, como constantes: https://en.wikipedia.org/wiki/List_of_acupuncture_points
const SP_1 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 1 , nombre: 'SP-1', chinoTradicional: '隱白', nombreTradicional: 'Yinbai'  });
const SP_2 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 2 , nombre: 'SP-2', chinoTradicional: '大都', nombreTradicional: 'Dadu'  });
const SP_3 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 3 , nombre: 'SP-3', chinoTradicional: '太白', nombreTradicional: 'Taibai'  });
const SP_4 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 4 , nombre: 'SP-4', chinoTradicional: '公孫', nombreTradicional: 'Gongsun'  });
const SP_5 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 5 , nombre: 'SP-5', chinoTradicional: '商丘', nombreTradicional: 'Shangqiu'  });
const SP_6 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 6 , nombre: 'SP-6', chinoTradicional: '三陰交', nombreTradicional: 'Sanyinjiao'  });
const SP_7 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 7 , nombre: 'SP-7', chinoTradicional: '漏谷', nombreTradicional: 'Lougu'  });
const SP_8 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 8 , nombre: 'SP-8', chinoTradicional: '地機', nombreTradicional: 'Diji'  });
const SP_9 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 9 , nombre: 'SP-9', chinoTradicional: '陰陵泉', nombreTradicional: 'Yinlingquan'  });
const SP_10 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 10 , nombre: 'SP-10', chinoTradicional: '血海', nombreTradicional: 'Xuehai'  });
const SP_11 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 11 , nombre: 'SP-11', chinoTradicional: '箕門', nombreTradicional: 'Jimen'  });
const SP_12 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 12 , nombre: 'SP-12', chinoTradicional: '沖門', nombreTradicional: 'Chongmen'  });
const SP_13 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 13 , nombre: 'SP-13', chinoTradicional: '府舍', nombreTradicional: 'Fushe'  });
const SP_14 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 14 , nombre: 'SP-14', chinoTradicional: '腹結(?)', nombreTradicional: 'Fujie'  });
const SP_15 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 15 , nombre: 'SP-15', chinoTradicional: '大横', nombreTradicional: 'Da heng'  });
const SP_16 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 16 , nombre: 'SP-16', chinoTradicional: '腹哀(?)', nombreTradicional: 'Fuai'  });
const SP_17 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 17 , nombre: 'SP-17', chinoTradicional: '食竇(?)', nombreTradicional: 'Shidou'  });
const SP_18 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 18 , nombre: 'SP-18', chinoTradicional: '天谿', nombreTradicional: 'Tianxi'  });
const SP_19 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 19 , nombre: 'SP-19', chinoTradicional: '胸鄉(?)', nombreTradicional: 'Xiongxiang'  });
const SP_20 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 20 , nombre: 'SP-20', chinoTradicional: '周榮(?)', nombreTradicional: 'Zhourong'  });
const SP_21 =  new Punto({canal: 'Canal.TAIYIN_PIE' , numero: 21 , nombre: 'SP-21', chinoTradicional: '大包', nombreTradicional: 'Dabao'  });
const HT_1 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 1 , nombre: 'HT-1', chinoTradicional: '極泉', nombreTradicional: 'Jiquan'  });
const HT_2 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 2 , nombre: 'HT-2', chinoTradicional: '青靈', nombreTradicional: 'Qingling'  });
const HT_3 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 3 , nombre: 'HT-3', chinoTradicional: '少海', nombreTradicional: 'Shaohai'  });
const HT_4 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 4 , nombre: 'HT-4', chinoTradicional: '靈道', nombreTradicional: 'Lingdao'  });
const HE_5 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 5 , nombre: 'HE-5', chinoTradicional: '通里', nombreTradicional: 'Tongli'  });
const HE_6 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 6 , nombre: 'HE-6', chinoTradicional: '陰郄', nombreTradicional: 'Yinxi'  });
const HE_7 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 7 , nombre: 'HE-7', chinoTradicional: '神門', nombreTradicional: 'Shenmen'  });
const HE_8 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 8 , nombre: 'HE-8', chinoTradicional: '少府', nombreTradicional: 'Shaofu'  });
const HE_9 =  new Punto({canal: 'Canal.SHAOYIN_MANO' , numero: 9 , nombre: 'HE-9', chinoTradicional: '少沖', nombreTradicional: 'Shaochong'  });
const Du_1 =  new Punto({canal: 'Canal.DUMAI' , numero: 1 , nombre: 'Du-1', chinoTradicional: '長強', nombreTradicional: 'cháng qiáng'  });
const Du_2 =  new Punto({canal: 'Canal.DUMAI' , numero: 2 , nombre: 'Du-2', chinoTradicional: '腰俞', nombreTradicional: 'yāo shū(?)'  });
const Du_3 =  new Punto({canal: 'Canal.DUMAI' , numero: 3 , nombre: 'Du-3', chinoTradicional: '腰陽關', nombreTradicional: 'yāo yáng guān'  });
const Du_4 =  new Punto({canal: 'Canal.DUMAI' , numero: 4 , nombre: 'Du-4', chinoTradicional: '命門', nombreTradicional: 'mìng mén'  });
const Du_5 =  new Punto({canal: 'Canal.DUMAI' , numero: 5 , nombre: 'Du-5', chinoTradicional: '懸樞', nombreTradicional: 'xuán shū'  });
const Du_6 =  new Punto({canal: 'Canal.DUMAI' , numero: 6 , nombre: 'Du-6', chinoTradicional: '脊中(?)', nombreTradicional: 'jì zhōng?'  });
const Du_7 =  new Punto({canal: 'Canal.DUMAI' , numero: 7 , nombre: 'Du-7', chinoTradicional: '中樞', nombreTradicional: 'zhōng shū'  });
const Du_8 =  new Punto({canal: 'Canal.DUMAI' , numero: 8 , nombre: 'Du-8', chinoTradicional: '筋縮', nombreTradicional: 'jīn suō'  });
const Du_9 =  new Punto({canal: 'Canal.DUMAI' , numero: 9 , nombre: 'Du-9', chinoTradicional: '至陽', nombreTradicional: 'zhì yáng'  });
const Du_10 =  new Punto({canal: 'Canal.DUMAI' , numero: 10 , nombre: 'Du-10', chinoTradicional: '霊台', nombreTradicional: 'líng tái'  });
const Du_11 =  new Punto({canal: 'Canal.DUMAI' , numero: 11 , nombre: 'Du-11', chinoTradicional: '神道(?)', nombreTradicional: 'shén dào(?)'  });
const Du_12 =  new Punto({canal: 'Canal.DUMAI' , numero: 12 , nombre: 'Du-12', chinoTradicional: '身柱(?)', nombreTradicional: 'shēn zhù(?)'  });
const Du_13 =  new Punto({canal: 'Canal.DUMAI' , numero: 13 , nombre: 'Du-13', chinoTradicional: '陶道', nombreTradicional: 'táo dào'  });
const Du_14 =  new Punto({canal: 'Canal.DUMAI' , numero: 14 , nombre: 'Du-14', chinoTradicional: '大椎', nombreTradicional: 'dà zhuī'  });
const Du_15 =  new Punto({canal: 'Canal.DUMAI' , numero: 15 , nombre: 'Du-15', chinoTradicional: '瘂門 (唖門)', nombreTradicional: 'yǎ mén'  });
const Du_16 =  new Punto({canal: 'Canal.DUMAI' , numero: 16 , nombre: 'Du-16', chinoTradicional: '風府', nombreTradicional: 'fēng fǔ'  });
const Du_17 =  new Punto({canal: 'Canal.DUMAI' , numero: 17 , nombre: 'Du-17', chinoTradicional: '腦戶', nombreTradicional: 'nǎo hù'  });
const Du_18 =  new Punto({canal: 'Canal.DUMAI' , numero: 18 , nombre: 'Du-18', chinoTradicional: '強間', nombreTradicional: 'qiáng jiān'  });
const Du_19 =  new Punto({canal: 'Canal.DUMAI' , numero: 19 , nombre: 'Du-19', chinoTradicional: '後頂', nombreTradicional: 'hòu dǐng'  });
const Du_20 =  new Punto({canal: 'Canal.DUMAI' , numero: 20 , nombre: 'Du-20', chinoTradicional: '百會', nombreTradicional: 'bǎi huì'  });
const Du_21 =  new Punto({canal: 'Canal.DUMAI' , numero: 21 , nombre: 'Du-21', chinoTradicional: '前頂(?)', nombreTradicional: 'qián dǐng(?)'  });
const Du_22 =  new Punto({canal: 'Canal.DUMAI' , numero: 22 , nombre: 'Du-22', chinoTradicional: '囟會', nombreTradicional: 'xìn huì'  });
const Du_23 =  new Punto({canal: 'Canal.DUMAI' , numero: 23 , nombre: 'Du-23', chinoTradicional: '上星(?)', nombreTradicional: 'shàng xīng(?)'  });
const Du_24 =  new Punto({canal: 'Canal.DUMAI' , numero: 24 , nombre: 'Du-24', chinoTradicional: '神庭', nombreTradicional: 'shén tíng'  });
const Du_25 =  new Punto({canal: 'Canal.DUMAI' , numero: 25 , nombre: 'Du-25', chinoTradicional: '素髎(?)', nombreTradicional: 'sù liáo(?)'  });
const Du_26 =  new Punto({canal: 'Canal.DUMAI' , numero: 26 , nombre: 'Du-26', chinoTradicional: '水溝', nombreTradicional: 'rén zhōng'  });
const Du_27 =  new Punto({canal: 'Canal.DUMAI' , numero: 27 , nombre: 'Du-27', chinoTradicional: '兌端', nombreTradicional: 'duì duān'  });
const Du_28 =  new Punto({canal: 'Canal.DUMAI' , numero: 28 , nombre: 'Du-28', chinoTradicional: '齦交', nombreTradicional: 'yín jiāo'  });
const St_1 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 1 , nombre: 'St-1', chinoTradicional: '承泣', nombreTradicional: 'Chengqi'  });
const St_2 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 2 , nombre: 'St-2', chinoTradicional: '四白(?)', nombreTradicional: 'Sibai'  });
const St_3 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 3 , nombre: 'St-3', chinoTradicional: '巨髎', nombreTradicional: 'Juliao'  });
const St_4 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 4 , nombre: 'St-4', chinoTradicional: '地倉', nombreTradicional: 'Dicang'  });
const St_5 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 5 , nombre: 'St-5', chinoTradicional: '大迎', nombreTradicional: 'Daying'  });
const St_6 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 6 , nombre: 'St-6', chinoTradicional: '頰車', nombreTradicional: 'Jiache'  });
const St_7 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 7 , nombre: 'St-7', chinoTradicional: '下關', nombreTradicional: 'Xiaguan'  });
const St_8 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 8 , nombre: 'St-8', chinoTradicional: '頭維', nombreTradicional: 'Touwei'  });
const St_9 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 9 , nombre: 'St-9', chinoTradicional: '人迎', nombreTradicional: 'Renying'  });
const St_10 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 10 , nombre: 'St-10', chinoTradicional: '水突(?)', nombreTradicional: 'Shuitu'  });
const St_11 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 11 , nombre: 'St-11', chinoTradicional: '氣舍', nombreTradicional: 'Qishe'  });
const St_12 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 12 , nombre: 'St-12', chinoTradicional: '缺盆', nombreTradicional: 'Quepen'  });
const St_13 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 13 , nombre: 'St-13', chinoTradicional: '氣戶', nombreTradicional: 'Qihu'  });
const St_14 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 14 , nombre: 'St-14', chinoTradicional: '庫房(?)', nombreTradicional: 'Kufang'  });
const St_15 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 15 , nombre: 'St-15', chinoTradicional: '屋翳(?)', nombreTradicional: 'Wuyi'  });
const St_16 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 16 , nombre: 'St-16', chinoTradicional: '膺窗(?)', nombreTradicional: 'Yingchuang'  });
const St_17 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 17 , nombre: 'St-17', chinoTradicional: '乳中(?)', nombreTradicional: 'Ruzhong'  });
const St_18 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 18 , nombre: 'St-18', chinoTradicional: '乳根', nombreTradicional: 'Rugen'  });
const St_19 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 19 , nombre: 'St-19', chinoTradicional: '不容(?)', nombreTradicional: 'Burong'  });
const St_20 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 20 , nombre: 'St-20', chinoTradicional: '承满(?)', nombreTradicional: 'Chengman'  });
const St_21 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 21 , nombre: 'St-21', chinoTradicional: '梁門(?)', nombreTradicional: 'Liangmen'  });
const St_22 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 22 , nombre: 'St-22', chinoTradicional: '關門', nombreTradicional: 'Guanmen'  });
const St_23 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 23 , nombre: 'St-23', chinoTradicional: '太乙(?)', nombreTradicional: 'Taiyi'  });
const St_24 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 24 , nombre: 'St-24', chinoTradicional: '滑肉門(?)', nombreTradicional: 'Huaroumen'  });
const St_25 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 25 , nombre: 'St-25', chinoTradicional: '天樞', nombreTradicional: 'Tianshu'  });
const St_26 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 26 , nombre: 'St-26', chinoTradicional: '外陵(?)', nombreTradicional: 'Wailing'  });
const St_27 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 27 , nombre: 'St-27', chinoTradicional: '大巨(?)', nombreTradicional: 'Daju'  });
const St_28 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 28 , nombre: 'St-28', chinoTradicional: '水道(?)', nombreTradicional: 'Shuidao'  });
const St_29 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 29 , nombre: 'St-29', chinoTradicional: '歸來 (归来)', nombreTradicional: 'Guilai'  });
const St_30 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 30 , nombre: 'St-30', chinoTradicional: '氣沖', nombreTradicional: 'Qichong'  });
const St_31 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 31 , nombre: 'St-31', chinoTradicional: '髀關', nombreTradicional: 'Biguan'  });
const St_32 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 32 , nombre: 'St-32', chinoTradicional: '伏兔(?)', nombreTradicional: 'Futu'  });
const St_33 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 33 , nombre: 'St-33', chinoTradicional: '阴市(?)', nombreTradicional: 'Yinshi'  });
const St_34 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 34 , nombre: 'St-34', chinoTradicional: '梁丘(?)', nombreTradicional: 'Liangqiu'  });
const St_35 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 35 , nombre: 'St-35', chinoTradicional: '犊鼻(?)', nombreTradicional: 'Dubi'  });
const St_36 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 36 , nombre: 'St-36', chinoTradicional: '足三里', nombreTradicional: 'Zusanli'  });
const St_37 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 37 , nombre: 'St-37', chinoTradicional: '上巨虛', nombreTradicional: 'Shangjuxu'  });
const St_38 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 38 , nombre: 'St-38', chinoTradicional: '條口(?)', nombreTradicional: 'Tiaokou'  });
const St_39 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 39 , nombre: 'St-39', chinoTradicional: '下巨虛', nombreTradicional: 'Xiajuxu'  });
const St_40 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 40 , nombre: 'St-40', chinoTradicional: '豐隆', nombreTradicional: 'Fenglong'  });
const St_41 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 41 , nombre: 'St-41', chinoTradicional: '解谿', nombreTradicional: 'Jiexi'  });
const St_42 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 42 , nombre: 'St-42', chinoTradicional: '沖陽', nombreTradicional: 'Chongyang'  });
const St_43 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 43 , nombre: 'St-43', chinoTradicional: '陷谷(?)', nombreTradicional: 'Xiangu'  });
const St_44 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 44 , nombre: 'St-44', chinoTradicional: '内庭', nombreTradicional: 'Neiting'  });
const St_45 =  new Punto({canal: 'Canal.YANGMING_PIE' , numero: 45 , nombre: 'St-45', chinoTradicional: '厲兌', nombreTradicional: 'Lidui'  });
const M_LE_8 =  new Punto({canal: '' , numero: null, nombre: 'M-LE-8', chinoTradicional: '八風', nombreTradicional: 'bā fēng' });
const M_UE_1 =  new Punto({canal: '' , numero: null, nombre: 'M-UE-1', chinoTradicional: '十宣', nombreTradicional: 'shí xuān' });
const M_UE_9 =  new Punto({canal: '' , numero: null, nombre: 'M-UE-9', chinoTradicional: '八邪', nombreTradicional: 'bā xié' });
const M_HN_3 =  new Punto({canal: '' , numero: null, nombre: 'M-HN-3', chinoTradicional: '印堂', nombreTradicional: 'yìn táng' });
const M_BW_35 =  new Punto({canal: '' , numero: null, nombre: 'M-BW-35', chinoTradicional: '華佗夾脊', nombreTradicional: 'huá túo jiā jǐ' });
const Liv_1 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 1 , nombre: 'Liv-1', chinoTradicional: '大敦', nombreTradicional: 'dà dūn'  });
const Liv_2 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 2 , nombre: 'Liv-2', chinoTradicional: '行間', nombreTradicional: 'xíng jiān'  });
const Liv_3 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 3 , nombre: 'Liv-3', chinoTradicional: '太沖', nombreTradicional: 'taì chōng'  });
const Liv_4 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 4 , nombre: 'Liv-4', chinoTradicional: '中封', nombreTradicional: 'zhōng fēng'  });
const Liv_5 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 5 , nombre: 'Liv-5', chinoTradicional: '蠡溝', nombreTradicional: 'lǐ gōu'  });
const Liv_6 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 6 , nombre: 'Liv-6', chinoTradicional: '中都', nombreTradicional: 'zhōng dū(?)'  });
const Liv_7 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 7 , nombre: 'Liv-7', chinoTradicional: '膝關(?)', nombreTradicional: 'xī guān(?)'  });
const Liv_8 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 8 , nombre: 'Liv-8', chinoTradicional: '曲泉', nombreTradicional: 'qū quán'  });
const Liv_9 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 9 , nombre: 'Liv-9', chinoTradicional: '陰包', nombreTradicional: 'yīn bāo(?)'  });
const Liv_10 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 10 , nombre: 'Liv-10', chinoTradicional: '足五里(?)', nombreTradicional: 'zú wǔ li?'  });
const Liv_11 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 11 , nombre: 'Liv-11', chinoTradicional: '陰廉', nombreTradicional: 'yīn lián'  });
const Liv_12 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 12 , nombre: 'Liv-12', chinoTradicional: '急脈', nombreTradicional: 'jí mài'  });
const Liv_13 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 13 , nombre: 'Liv-13', chinoTradicional: '章門', nombreTradicional: 'zhāng mén'  });
const Liv_14 =  new Punto({canal: 'Canal.JUEYIN_PIE' , numero: 14 , nombre: 'Liv-14', chinoTradicional: '期門', nombreTradicional: 'qí mén'  });
const SI_1 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 1 , nombre: 'SI-1', chinoTradicional: '少澤', nombreTradicional: 'Shaoze'  });
const SI_2 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 2 , nombre: 'SI-2', chinoTradicional: '前谷', nombreTradicional: 'Qiangu'  });
const SI_3 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 3 , nombre: 'SI-3', chinoTradicional: '後谿', nombreTradicional: 'Houxi'  });
const SI_4 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 4 , nombre: 'SI-4', chinoTradicional: '腕骨', nombreTradicional: 'Wangu'  });
const SI_5 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 5 , nombre: 'SI-5', chinoTradicional: '陽谷', nombreTradicional: 'Yanggu'  });
const SI_6 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 6 , nombre: 'SI-6', chinoTradicional: '養老', nombreTradicional: 'Yanglao'  });
const SI_7 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 7 , nombre: 'SI-7', chinoTradicional: '支正', nombreTradicional: 'Zhizheng'  });
const SI_8 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 8 , nombre: 'SI-8', chinoTradicional: '小海', nombreTradicional: 'Xiaohai'  });
const SI_9 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 9 , nombre: 'SI-9', chinoTradicional: '肩貞', nombreTradicional: 'Jianzhen'  });
const SI_10 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 10 , nombre: 'SI-10', chinoTradicional: '臑俞', nombreTradicional: 'Naoshu'  });
const SI_11 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 11 , nombre: 'SI-11', chinoTradicional: '天宗', nombreTradicional: 'Tianzong'  });
const SI_12 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 12 , nombre: 'SI-12', chinoTradicional: '秉風', nombreTradicional: 'Bingfeng'  });
const SI_13 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 13 , nombre: 'SI-13', chinoTradicional: '曲垣', nombreTradicional: 'Quyuan'  });
const SI_14 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 14 , nombre: 'SI-14', chinoTradicional: '肩外俞', nombreTradicional: 'Jianwaishu'  });
const SI_15 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 15 , nombre: 'SI-15', chinoTradicional: '肩中俞', nombreTradicional: 'Jianzhongshu'  });
const SI_16 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 16 , nombre: 'SI-16', chinoTradicional: '天窗', nombreTradicional: 'Tianchuang'  });
const SI_17 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 17 , nombre: 'SI-17', chinoTradicional: '天容', nombreTradicional: 'Tianrong'  });
const SI_18 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 18 , nombre: 'SI-18', chinoTradicional: '顴髎', nombreTradicional: 'Quanliao'  });
const SI_19 =  new Punto({canal: 'Canal.TAIYANG_MANO' , numero: 19 , nombre: 'SI-19', chinoTradicional: '聽宮', nombreTradicional: 'Tinggong'  });
const LI_1 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 1 , nombre: 'LI-1', chinoTradicional: '商陽', nombreTradicional: 'Shangyang'  });
const LI_2 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 2 , nombre: 'LI-2', chinoTradicional: '二間(?)', nombreTradicional: 'Erjian'  });
const LI_3 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 3 , nombre: 'LI-3', chinoTradicional: '三間(?)', nombreTradicional: 'Sanjian'  });
const LI_4 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 4 , nombre: 'LI-4', chinoTradicional: '合谷', nombreTradicional: 'He Gu'  });
const LI_5 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 5 , nombre: 'LI-5', chinoTradicional: '陽谿', nombreTradicional: 'Yangxi'  });
const LI_6 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 6 , nombre: 'LI-6', chinoTradicional: '偏歴', nombreTradicional: 'Pianli'  });
const LI_7 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 7 , nombre: 'LI-7', chinoTradicional: '溫溜', nombreTradicional: 'Wenliu'  });
const LI_8 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 8 , nombre: 'LI-8', chinoTradicional: '下廉(?)', nombreTradicional: 'Xialian'  });
const LI_9 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 9 , nombre: 'LI-9', chinoTradicional: '上廉(?)', nombreTradicional: 'Shanglian'  });
const LI_10 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 10 , nombre: 'LI-10', chinoTradicional: '手三里', nombreTradicional: 'Shousanli'  });
const LI_11 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 11 , nombre: 'LI-11', chinoTradicional: '曲池', nombreTradicional: 'Quchi'  });
const LI_12 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 12 , nombre: 'LI-12', chinoTradicional: '肘髎(?)', nombreTradicional: 'Zhouliao'  });
const LI_13 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 13 , nombre: 'LI-13', chinoTradicional: '手五里(?)', nombreTradicional: 'Shouwuli'  });
const LI_14 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 14 , nombre: 'LI-14', chinoTradicional: '臂臑', nombreTradicional: 'Binao'  });
const LI_15 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 15 , nombre: 'LI-15', chinoTradicional: '肩髃', nombreTradicional: 'Jianyu'  });
const LI_16 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 16 , nombre: 'LI-16', chinoTradicional: '巨骨', nombreTradicional: 'Jugu'  });
const LI_17 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 17 , nombre: 'LI-17', chinoTradicional: '天鼎(?)', nombreTradicional: 'Tianding'  });
const LI_18 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 18 , nombre: 'LI-18', chinoTradicional: '扶突(?)', nombreTradicional: 'Futu'  });
const LI_19 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 19 , nombre: 'LI-19', chinoTradicional: '口禾髎', nombreTradicional: 'Kouheliao'  });
const LI_20 =  new Punto({canal: 'Canal.YANGMING_MANO' , numero: 20 , nombre: 'LI-20', chinoTradicional: '迎香', nombreTradicional: 'Yingxiang'  });
const Pc_1 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 1 , nombre: 'Pc-1', chinoTradicional: '天池', nombreTradicional: 'Tianchi'  });
const Pc_2 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 2 , nombre: 'Pc-2', chinoTradicional: '天泉(?)', nombreTradicional: 'Tianquan'  });
const Pc_3 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 3 , nombre: 'Pc-3', chinoTradicional: '曲澤', nombreTradicional: 'Quze'  });
const Pc_4 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 4 , nombre: 'Pc-4', chinoTradicional: '郄門', nombreTradicional: 'Ximen'  });
const Pc_5 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 5 , nombre: 'Pc-5', chinoTradicional: '間使', nombreTradicional: 'Jianshi'  });
const Pc_6 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 6 , nombre: 'Pc-6', chinoTradicional: '內關', nombreTradicional: 'Neiguan'  });
const Pc_7 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 7 , nombre: 'Pc-7', chinoTradicional: '大陵', nombreTradicional: 'Daling'  });
const Pc_8 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 8 , nombre: 'Pc-8', chinoTradicional: '勞宮', nombreTradicional: 'Laogong'  });
const Pc_9 =  new Punto({canal: 'Canal.JUEYIN_MANO' , numero: 9 , nombre: 'Pc-9', chinoTradicional: '中衝', nombreTradicional: 'Zhongchong'  });
const LU_1 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 1 , nombre: 'LU-1', chinoTradicional: '中府', nombreTradicional: 'Zhongfu'  });
const LU_2 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 2 , nombre: 'LU-2', chinoTradicional: '雲門', nombreTradicional: 'Yunmen'  });
const LU_3 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 3 , nombre: 'LU-3', chinoTradicional: '天府(?)', nombreTradicional: 'Tianfu'  });
const LU_4 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 4 , nombre: 'LU-4', chinoTradicional: '俠白(?)', nombreTradicional: 'Xiabai'  });
const LU_5 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 5 , nombre: 'LU-5', chinoTradicional: '尺澤', nombreTradicional: 'Chize'  });
const LU_6 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 6 , nombre: 'LU-6', chinoTradicional: '孔最(?)', nombreTradicional: 'Kongzui'  });
const LU_7 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 7 , nombre: 'LU-7', chinoTradicional: '列缺', nombreTradicional: 'Lieque'  });
const LU_8 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 8 , nombre: 'LU-8', chinoTradicional: '經渠', nombreTradicional: 'Jingqu'  });
const LU_9 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 9 , nombre: 'LU-9', chinoTradicional: '太淵', nombreTradicional: 'Taiyuan'  });
const LU_10 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 10 , nombre: 'LU-10', chinoTradicional: '魚際', nombreTradicional: 'Yuji'  });
const LU_11 =  new Punto({canal: 'Canal.TAIYIN_MANO' , numero: 11 , nombre: 'LU-11', chinoTradicional: '少商', nombreTradicional: 'Shaoshang'  });
const Ren_1 =  new Punto({canal: 'Canal.RENMAI' , numero: 1 , nombre: 'Ren-1', chinoTradicional: '會陰', nombreTradicional: 'huì yīn'  });
const Ren_2 =  new Punto({canal: 'Canal.RENMAI' , numero: 2 , nombre: 'Ren-2', chinoTradicional: '曲骨', nombreTradicional: 'qū gǔ'  });
const Ren_3 =  new Punto({canal: 'Canal.RENMAI' , numero: 3 , nombre: 'Ren-3', chinoTradicional: '中極', nombreTradicional: 'zhōng jí'  });
const Ren_4 =  new Punto({canal: 'Canal.RENMAI' , numero: 4 , nombre: 'Ren-4', chinoTradicional: '關元', nombreTradicional: 'guān yuán'  });
const Ren_5 =  new Punto({canal: 'Canal.RENMAI' , numero: 5 , nombre: 'Ren-5', chinoTradicional: '石門(?)', nombreTradicional: 'shí mén(?)'  });
const Ren_6 =  new Punto({canal: 'Canal.RENMAI' , numero: 6 , nombre: 'Ren-6', chinoTradicional: '氣海', nombreTradicional: 'qì hǎi'  });
const Ren_7 =  new Punto({canal: 'Canal.RENMAI' , numero: 7 , nombre: 'Ren-7', chinoTradicional: '陰交', nombreTradicional: 'yīn jiāo'  });
const Ren_8 =  new Punto({canal: 'Canal.RENMAI' , numero: 8 , nombre: 'Ren-8', chinoTradicional: '神闕', nombreTradicional: 'shén què'  });
const Ren_9 =  new Punto({canal: 'Canal.RENMAI' , numero: 9 , nombre: 'Ren-9', chinoTradicional: '水分(?)', nombreTradicional: 'shuǐ fēn(?)'  });
const Ren_10 =  new Punto({canal: 'Canal.RENMAI' , numero: 10 , nombre: 'Ren-10', chinoTradicional: '下脘', nombreTradicional: 'xià wǎn [or xià guǎn]'  });
const Ren_11 =  new Punto({canal: 'Canal.RENMAI' , numero: 11 , nombre: 'Ren-11', chinoTradicional: '建里(?)', nombreTradicional: 'jiàn lǐ(?)'  });
const Ren_12 =  new Punto({canal: 'Canal.RENMAI' , numero: 12 , nombre: 'Ren-12', chinoTradicional: '中脘', nombreTradicional: 'zhōng wǎn [or zhōng guǎn]'  });
const Ren_13 =  new Punto({canal: 'Canal.RENMAI' , numero: 13 , nombre: 'Ren-13', chinoTradicional: '上脘', nombreTradicional: 'shàng wǎn [or shàng guǎn]'  });
const Ren_14 =  new Punto({canal: 'Canal.RENMAI' , numero: 14 , nombre: 'Ren-14', chinoTradicional: '巨闕(?)', nombreTradicional: 'jù què(?)'  });
const Ren_15 =  new Punto({canal: 'Canal.RENMAI' , numero: 15 , nombre: 'Ren-15', chinoTradicional: '鳩尾(?)', nombreTradicional: 'jiū wěi(?)'  });
const Ren_16 =  new Punto({canal: 'Canal.RENMAI' , numero: 16 , nombre: 'Ren-16', chinoTradicional: '中庭(?)', nombreTradicional: 'zhōng tíng(?)'  });
const Ren_17 =  new Punto({canal: 'Canal.RENMAI' , numero: 17 , nombre: 'Ren-17', chinoTradicional: '膻中', nombreTradicional: 'shān zhōng'  });
const Ren_18 =  new Punto({canal: 'Canal.RENMAI' , numero: 18 , nombre: 'Ren-18', chinoTradicional: '玉堂(?)', nombreTradicional: 'yù táng(?)'  });
const Ren_19 =  new Punto({canal: 'Canal.RENMAI' , numero: 19 , nombre: 'Ren-19', chinoTradicional: '紫宮(?)', nombreTradicional: 'zǐ gōng(?)'  });
const Ren_20 =  new Punto({canal: 'Canal.RENMAI' , numero: 20 , nombre: 'Ren-20', chinoTradicional: '華蓋', nombreTradicional: 'huá gài'  });
const Ren_21 =  new Punto({canal: 'Canal.RENMAI' , numero: 21 , nombre: 'Ren-21', chinoTradicional: '璇璣', nombreTradicional: 'xuán jī'  });
const Ren_22 =  new Punto({canal: 'Canal.RENMAI' , numero: 22 , nombre: 'Ren-22', chinoTradicional: '天突', nombreTradicional: 'tiān tū'  });
const Ren_23 =  new Punto({canal: 'Canal.RENMAI' , numero: 23 , nombre: 'Ren-23', chinoTradicional: '廉泉', nombreTradicional: 'lián quán'  });
const Ren_24 =  new Punto({canal: 'Canal.RENMAI' , numero: 24 , nombre: 'Ren-24', chinoTradicional: '承漿', nombreTradicional: 'chéng jiāng'  });
const Kd_1 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 1 , nombre: 'Kd-1', chinoTradicional: '涌泉', nombreTradicional: 'Yong Quan'  });
const Kd_2 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 2 , nombre: 'Kd-2', chinoTradicional: '然谷', nombreTradicional: 'Rangu'  });
const Kd_3 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 3 , nombre: 'Kd-3', chinoTradicional: '太谿', nombreTradicional: 'Taixi'  });
const Kd_4 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 4 , nombre: 'Kd-4', chinoTradicional: '大鐘', nombreTradicional: 'Dazhong'  });
const Kd_5 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 5 , nombre: 'Kd-5', chinoTradicional: '水泉', nombreTradicional: 'Shuiquan'  });
const Kd_6 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 6 , nombre: 'Kd-6', chinoTradicional: '照海', nombreTradicional: 'Zhaohai'  });
const Kd_7 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 7 , nombre: 'Kd-7', chinoTradicional: '復溜', nombreTradicional: 'Fuliu'  });
const Kd_8 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 8 , nombre: 'Kd-8', chinoTradicional: '交信', nombreTradicional: 'Jiaoxin'  });
const Kd_9 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 9 , nombre: 'Kd-9', chinoTradicional: '築賓', nombreTradicional: 'Zhubin'  });
const Kd_10 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 10 , nombre: 'Kd-10', chinoTradicional: '陰谷', nombreTradicional: 'Yingu'  });
const Kd_11 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 11 , nombre: 'Kd-11', chinoTradicional: '橫骨', nombreTradicional: 'Henggu'  });
const Kd_12 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 12 , nombre: 'Kd-12', chinoTradicional: '大赫(?)', nombreTradicional: 'Dahe'  });
const Kd_13 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 13 , nombre: 'Kd-13', chinoTradicional: '氣穴', nombreTradicional: 'Qixue'  });
const Kd_14 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 14 , nombre: 'Kd-14', chinoTradicional: '四滿', nombreTradicional: 'Siman'  });
const Kd_15 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 15 , nombre: 'Kd-15', chinoTradicional: '中注(?)', nombreTradicional: 'Zhongzhu'  });
const Kd_16 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 16 , nombre: 'Kd-16', chinoTradicional: '肓俞', nombreTradicional: 'Huangshu'  });
const Kd_17 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 17 , nombre: 'Kd-17', chinoTradicional: '商曲(?)', nombreTradicional: 'Shangqu'  });
const Kd_18 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 18 , nombre: 'Kd-18', chinoTradicional: '石關(?)', nombreTradicional: 'Shiguan'  });
const Kd_19 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 19 , nombre: 'Kd-19', chinoTradicional: '陰都', nombreTradicional: 'Yindu'  });
const Kd_20 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 20 , nombre: 'Kd-20', chinoTradicional: '腹通谷', nombreTradicional: 'Futonggu'  });
const Kd_21 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 21 , nombre: 'Kd-21', chinoTradicional: '幽門', nombreTradicional: 'Youmen'  });
const Kd_22 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 22 , nombre: 'Kd-22', chinoTradicional: '步廊(?)', nombreTradicional: 'Bulang'  });
const Kd_23 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 23 , nombre: 'Kd-23', chinoTradicional: '神封', nombreTradicional: 'Shenfeng'  });
const Kd_24 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 24 , nombre: 'Kd-24', chinoTradicional: '靈墟', nombreTradicional: 'Lingxu'  });
const Kd_25 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 25 , nombre: 'Kd-25', chinoTradicional: '神藏', nombreTradicional: 'Shencang'  });
const Kd_26 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 26 , nombre: 'Kd-26', chinoTradicional: '彧中', nombreTradicional: 'Yuzhong'  });
const Kd_27 =  new Punto({canal: 'Canal.SHAOYIN_PIE' , numero: 27 , nombre: 'Kd-27', chinoTradicional: '俞府', nombreTradicional: 'Shufu'  });
const SJ_1 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 1 , nombre: 'SJ-1', chinoTradicional: '關衝', nombreTradicional: 'Guanchong'  });
const SJ_2 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 2 , nombre: 'SJ-2', chinoTradicional: '液門(?)', nombreTradicional: 'Yemen'  });
const SJ_3 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 3 , nombre: 'SJ-3', chinoTradicional: '中渚(?)', nombreTradicional: 'Zhongzhu'  });
const SJ_4 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 4 , nombre: 'SJ-4', chinoTradicional: '陽池(?)', nombreTradicional: 'Yangchi'  });
const SJ_5 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 5 , nombre: 'SJ-5', chinoTradicional: '外關', nombreTradicional: 'Waiguan'  });
const SJ_6 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 6 , nombre: 'SJ-6', chinoTradicional: '支溝(?)', nombreTradicional: 'Zhigou'  });
const SJ_7 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 7 , nombre: 'SJ-7', chinoTradicional: '會宗', nombreTradicional: 'Huizong'  });
const SJ_8 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 8 , nombre: 'SJ-8', chinoTradicional: '三陽絡(?)', nombreTradicional: 'Sanyangluo'  });
const SJ_9 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 9 , nombre: 'SJ-9', chinoTradicional: '四瀆(?)', nombreTradicional: 'Sidu'  });
const SJ_10 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 10 , nombre: 'SJ-10', chinoTradicional: '天井', nombreTradicional: 'Tianjing'  });
const SJ_11 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 11 , nombre: 'SJ-11', chinoTradicional: '清冷淵(?)', nombreTradicional: 'Qinglengyuan'  });
const SJ_12 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 12 , nombre: 'SJ-12', chinoTradicional: '消濼(?)', nombreTradicional: 'Xiaoluo'  });
const SJ_13 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 13 , nombre: 'SJ-13', chinoTradicional: '臑會(?)', nombreTradicional: 'Naohui'  });
const SJ_14 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 14 , nombre: 'SJ-14', chinoTradicional: '肩髎(?)', nombreTradicional: 'Jianliao'  });
const SJ_15 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 15 , nombre: 'SJ-15', chinoTradicional: '天髎', nombreTradicional: 'Tianliao'  });
const SJ_16 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 16 , nombre: 'SJ-16', chinoTradicional: '天牖(?)', nombreTradicional: 'Tianyou'  });
const SJ_17 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 17 , nombre: 'SJ-17', chinoTradicional: '翳風', nombreTradicional: 'Yifeng'  });
const SJ_18 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 18 , nombre: 'SJ-18', chinoTradicional: '契脈?', nombreTradicional: 'Qimai'  });
const SJ_19 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 19 , nombre: 'SJ-19', chinoTradicional: '顱息(?)', nombreTradicional: 'Luxi'  });
const SJ_20 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 20 , nombre: 'SJ-20', chinoTradicional: '角孫', nombreTradicional: 'Jiaosun'  });
const SJ_21 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 21 , nombre: 'SJ-21', chinoTradicional: '耳門(?)', nombreTradicional: 'Ermen'  });
const SJ_22 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 22 , nombre: 'SJ-22', chinoTradicional: '耳和髎', nombreTradicional: 'Erheliao'  });
const SJ_23 =  new Punto({canal: 'Canal.SHAOYANG_MANO' , numero: 23 , nombre: 'SJ-23', chinoTradicional: '絲竹空', nombreTradicional: 'Sizhukong'  });
const Bl_1 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 1 , nombre: 'Bl-1', chinoTradicional: '睛明', nombreTradicional: 'Jingming'  });
const Bl_2 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 2 , nombre: 'Bl-2', chinoTradicional: '攢竹', nombreTradicional: 'Zanzhu'  });
const Bl_3 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 3 , nombre: 'Bl-3', chinoTradicional: '眉衝', nombreTradicional: 'Meichong'  });
const Bl_4 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 4 , nombre: 'Bl-4', chinoTradicional: '曲差(?)', nombreTradicional: 'Quchai'  });
const Bl_5 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 5 , nombre: 'Bl-5', chinoTradicional: '五處', nombreTradicional: 'Wuchu'  });
const Bl_6 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 6 , nombre: 'Bl-6', chinoTradicional: '承光(?)', nombreTradicional: 'Chengguang'  });
const Bl_7 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 7 , nombre: 'Bl-7', chinoTradicional: '通天(?)', nombreTradicional: 'Tongtian'  });
const Bl_8 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 8 , nombre: 'Bl-8', chinoTradicional: '絡卻', nombreTradicional: 'Luoque'  });
const Bl_9 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 9 , nombre: 'Bl-9', chinoTradicional: '玉枕(?)', nombreTradicional: 'Yuzhen'  });
const Bl_10 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 10 , nombre: 'Bl-10', chinoTradicional: '天柱(?)', nombreTradicional: 'Tianzhu'  });
const Bl_11 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 11 , nombre: 'Bl-11', chinoTradicional: '大杼', nombreTradicional: 'Dazhu'  });
const Bl_12 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 12 , nombre: 'Bl-12', chinoTradicional: '風門', nombreTradicional: 'Fengmen'  });
const Bl_13 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 13 , nombre: 'Bl-13', chinoTradicional: '肺俞', nombreTradicional: 'Feishu'  });
const Bl_14 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 14 , nombre: 'Bl-14', chinoTradicional: '厥陰俞', nombreTradicional: 'Jueyinshu'  });
const Bl_15 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 15 , nombre: 'Bl-15', chinoTradicional: '心俞(?)', nombreTradicional: 'Xinshu'  });
const Bl_16 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 16 , nombre: 'Bl-16', chinoTradicional: '督俞', nombreTradicional: 'Dushu'  });
const Bl_17 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 17 , nombre: 'Bl-17', chinoTradicional: '膈俞', nombreTradicional: 'Geshu'  });
const Bl_18 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 18 , nombre: 'Bl-18', chinoTradicional: '肝俞', nombreTradicional: 'Ganshu'  });
const Bl_19 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 19 , nombre: 'Bl-19', chinoTradicional: '膽俞', nombreTradicional: 'Danshu'  });
const Bl_20 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 20 , nombre: 'Bl-20', chinoTradicional: '脾俞', nombreTradicional: 'Pishu'  });
const Bl_21 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 21 , nombre: 'Bl-21', chinoTradicional: '胃俞', nombreTradicional: 'Weishu'  });
const Bl_22 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 22 , nombre: 'Bl-22', chinoTradicional: '三焦俞', nombreTradicional: 'Sanjiaoshu'  });
const Bl_23 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 23 , nombre: 'Bl-23', chinoTradicional: '腎俞', nombreTradicional: 'Shenshu'  });
const Bl_24 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 24 , nombre: 'Bl-24', chinoTradicional: '氣海俞', nombreTradicional: 'Qihaishu'  });
const Bl_25 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 25 , nombre: 'Bl-25', chinoTradicional: '大腸俞', nombreTradicional: 'Dachangshu'  });
const Bl_26 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 26 , nombre: 'Bl-26', chinoTradicional: '關元俞', nombreTradicional: 'Guanyuanshu'  });
const Bl_27 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 27 , nombre: 'Bl-27', chinoTradicional: '小腸俞', nombreTradicional: 'Xiaochangshu'  });
const Bl_28 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 28 , nombre: 'Bl-28', chinoTradicional: '膀胱俞(?)', nombreTradicional: 'Pangguangshu'  });
const Bl_29 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 29 , nombre: 'Bl-29', chinoTradicional: '中膂俞(?)', nombreTradicional: 'Zhonglushu'  });
const Bl_30 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 30 , nombre: 'Bl-30', chinoTradicional: '白環俞', nombreTradicional: 'Baihuanshu'  });
const Bl_31 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 31 , nombre: 'Bl-31', chinoTradicional: '上髎(?)', nombreTradicional: 'Shangliao'  });
const Bl_32 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 32 , nombre: 'Bl-32', chinoTradicional: '次髎(?)', nombreTradicional: 'Ciliao'  });
const Bl_33 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 33 , nombre: 'Bl-33', chinoTradicional: '中髎(?)', nombreTradicional: 'Zhongliao'  });
const Bl_34 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 34 , nombre: 'Bl-34', chinoTradicional: '下髎(?)', nombreTradicional: 'Xialiao'  });
const Bl_35 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 35 , nombre: 'Bl-35', chinoTradicional: '會陽', nombreTradicional: 'Huiyang'  });
const Bl_36 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 36 , nombre: 'Bl-36', chinoTradicional: '承扶(?)', nombreTradicional: 'Chengfu'  });
const Bl_37 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 37 , nombre: 'Bl-37', chinoTradicional: '殷門', nombreTradicional: 'Yinmen'  });
const Bl_38 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 38 , nombre: 'Bl-38', chinoTradicional: '浮郄', nombreTradicional: 'Fuxi'  });
const Bl_39 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 39 , nombre: 'Bl-39', chinoTradicional: '委陽', nombreTradicional: 'Weiyang'  });
const Bl_40 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 40 , nombre: 'Bl-40', chinoTradicional: '委中', nombreTradicional: 'Weizhong'  });
const Bl_41 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 41 , nombre: 'Bl-41', chinoTradicional: '附分', nombreTradicional: 'Fufen'  });
const Bl_42 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 42 , nombre: 'Bl-42', chinoTradicional: '魄戶', nombreTradicional: 'Pohu'  });
const Bl_43 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 43 , nombre: 'Bl-43', chinoTradicional: '膏肓俞', nombreTradicional: 'Gaohuangshu'  });
const Bl_44 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 44 , nombre: 'Bl-44', chinoTradicional: '神堂(?)', nombreTradicional: 'Shentang'  });
const Bl_45 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 45 , nombre: 'Bl-45', chinoTradicional: '譩譆(?)', nombreTradicional: 'Yixi'  });
const Bl_46 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 46 , nombre: 'Bl-46', chinoTradicional: '膈關', nombreTradicional: 'Geguan'  });
const Bl_47 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 47 , nombre: 'Bl-47', chinoTradicional: '魂門', nombreTradicional: 'Hunmen'  });
const Bl_48 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 48 , nombre: 'Bl-48', chinoTradicional: '陽綱', nombreTradicional: 'Yanggang'  });
const Bl_49 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 49 , nombre: 'Bl-49', chinoTradicional: '意舍(?)', nombreTradicional: 'Yishe'  });
const Bl_50 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 50 , nombre: 'Bl-50', chinoTradicional: '胃倉', nombreTradicional: 'Weicang'  });
const Bl_51 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 51 , nombre: 'Bl-51', chinoTradicional: '肓門', nombreTradicional: 'Huangmen'  });
const Bl_52 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 52 , nombre: 'Bl-52', chinoTradicional: '志室(?)', nombreTradicional: 'Zhishi'  });
const Bl_53 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 53 , nombre: 'Bl-53', chinoTradicional: '胞肓(?)', nombreTradicional: 'Baohuang'  });
const Bl_54 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 54 , nombre: 'Bl-54', chinoTradicional: '秩邊', nombreTradicional: 'Zhibian'  });
const Bl_55 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 55 , nombre: 'Bl-55', chinoTradicional: '合陽', nombreTradicional: 'Heyang'  });
const Bl_56 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 56 , nombre: 'Bl-56', chinoTradicional: '承筋(?)', nombreTradicional: 'Chengjin'  });
const Bl_57 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 57 , nombre: 'Bl-57', chinoTradicional: '承山(?)', nombreTradicional: 'Chengshan'  });
const Bl_58 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 58 , nombre: 'Bl-58', chinoTradicional: '飛陽', nombreTradicional: 'Feiyang'  });
const Bl_59 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 59 , nombre: 'Bl-59', chinoTradicional: '跗陽', nombreTradicional: 'Fuyang'  });
const Bl_60 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 60 , nombre: 'Bl-60', chinoTradicional: '昆侖', nombreTradicional: 'Kunlun'  });
const Bl_61 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 61 , nombre: 'Bl-61', chinoTradicional: '僕參', nombreTradicional: 'Pucan'  });
const Bl_62 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 62 , nombre: 'Bl-62', chinoTradicional: '申脈', nombreTradicional: 'Shenmai'  });
const Bl_63 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 63 , nombre: 'Bl-63', chinoTradicional: '金門', nombreTradicional: 'Jinmen'  });
const Bl_64 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 64 , nombre: 'Bl-64', chinoTradicional: '京骨(?)', nombreTradicional: 'Jinggu'  });
const Bl_65 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 65 , nombre: 'Bl-65', chinoTradicional: '束骨(?)', nombreTradicional: 'Shugu'  });
const Bl_66 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 66 , nombre: 'Bl-66', chinoTradicional: '足通谷', nombreTradicional: 'Zutonggu'  });
const Bl_67 =  new Punto({canal: 'Canal.TAIYANG_PIE' , numero: 67 , nombre: 'Bl-67', chinoTradicional: '至陰', nombreTradicional: 'Zhiyin'  });
const Gb_1 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 1 , nombre: 'Gb-1', chinoTradicional: '瞳子髎', nombreTradicional: 'Tongziliao'  });
const Gb_2 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 2 , nombre: 'Gb-2', chinoTradicional: '聽會', nombreTradicional: 'Tinghui'  });
const Gb_3 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 3 , nombre: 'Gb-3', chinoTradicional: '上關', nombreTradicional: 'Shangguan'  });
const Gb_4 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 4 , nombre: 'Gb-4', chinoTradicional: '頷厭', nombreTradicional: 'Hanyan'  });
const Gb_5 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 5 , nombre: 'Gb-5', chinoTradicional: '懸顱', nombreTradicional: 'Xuanlu'  });
const Gb_6 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 6 , nombre: 'Gb-6', chinoTradicional: '懸厘', nombreTradicional: 'Xuanli'  });
const Gb_7 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 7 , nombre: 'Gb-7', chinoTradicional: '曲鬢', nombreTradicional: 'Qubin'  });
const Gb_8 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 8 , nombre: 'Gb-8', chinoTradicional: '率谷', nombreTradicional: 'Shuaigu'  });
const Gb_9 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 9 , nombre: 'Gb-9', chinoTradicional: '天沖', nombreTradicional: 'Tianchong'  });
const Gb_10 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 10 , nombre: 'Gb-10', chinoTradicional: '浮白', nombreTradicional: 'Fubai'  });
const Gb_11 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 11 , nombre: 'Gb-11', chinoTradicional: '頭竅陰', nombreTradicional: 'Touqiaoyin'  });
const Gb_12 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 12 , nombre: 'Gb-12', chinoTradicional: '完骨', nombreTradicional: 'Wangu'  });
const Gb_13 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 13 , nombre: 'Gb-13', chinoTradicional: '本神', nombreTradicional: 'Benshen'  });
const Gb_14 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 14 , nombre: 'Gb-14', chinoTradicional: '陽白', nombreTradicional: 'Yangbai'  });
const Gb_15 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 15 , nombre: 'Gb-15', chinoTradicional: '頭臨泣', nombreTradicional: 'Toulinqi'  });
const Gb_16 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 16 , nombre: 'Gb-16', chinoTradicional: '目窗(?)', nombreTradicional: 'Muchuang'  });
const Gb_17 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 17 , nombre: 'Gb-17', chinoTradicional: '正營', nombreTradicional: 'Zhengying'  });
const Gb_18 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 18 , nombre: 'Gb-18', chinoTradicional: '承靈', nombreTradicional: 'Chengling'  });
const Gb_19 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 19 , nombre: 'Gb-19', chinoTradicional: '腦空', nombreTradicional: 'Naokong'  });
const Gb_20 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 20 , nombre: 'Gb-20', chinoTradicional: '風池', nombreTradicional: 'Fengchi'  });
const Gb_21 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 21 , nombre: 'Gb-21', chinoTradicional: '肩井', nombreTradicional: 'Jianjing'  });
const Gb_22 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 22 , nombre: 'Gb-22', chinoTradicional: '淵腋', nombreTradicional: 'Yuanye'  });
const Gb_23 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 23 , nombre: 'Gb-23', chinoTradicional: '輒筋', nombreTradicional: 'Zhejin'  });
const Gb_24 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 24 , nombre: 'Gb-24', chinoTradicional: '日月', nombreTradicional: 'Riyue'  });
const Gb_25 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 25 , nombre: 'Gb-25', chinoTradicional: '京門', nombreTradicional: 'Jingmen'  });
const Gb_26 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 26 , nombre: 'Gb-26', chinoTradicional: '帶脈', nombreTradicional: 'Daimai'  });
const Gb_27 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 27 , nombre: 'Gb-27', chinoTradicional: '五樞', nombreTradicional: 'Wushu'  });
const Gb_28 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 28 , nombre: 'Gb-28', chinoTradicional: '維道', nombreTradicional: 'Weidao'  });
const Gb_29 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 29 , nombre: 'Gb-29', chinoTradicional: '居髎', nombreTradicional: 'Juliao'  });
const Gb_30 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 30 , nombre: 'Gb-30', chinoTradicional: '環跳', nombreTradicional: 'Huantiao'  });
const Gb_31 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 31 , nombre: 'Gb-31', chinoTradicional: '風市', nombreTradicional: 'Fengshi'  });
const Gb_32 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 32 , nombre: 'Gb-32', chinoTradicional: '中瀆', nombreTradicional: 'Zhongdu'  });
const Gb_33 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 33 , nombre: 'Gb-33', chinoTradicional: '膝陽關', nombreTradicional: 'Xiyangguan'  });
const Gb_34 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 34 , nombre: 'Gb-34', chinoTradicional: '陽陵泉', nombreTradicional: 'Yanglingquan'  });
const Gb_35 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 35 , nombre: 'Gb-35', chinoTradicional: '陽交', nombreTradicional: 'Yangjiao'  });
const Gb_36 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 36 , nombre: 'Gb-36', chinoTradicional: '外丘(?)', nombreTradicional: 'Waiqiu'  });
const Gb_37 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 37 , nombre: 'Gb-37', chinoTradicional: '光明(?)', nombreTradicional: 'Guangming'  });
const Gb_38 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 38 , nombre: 'Gb-38', chinoTradicional: '陽輔', nombreTradicional: 'Yangfu'  });
const Gb_39 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 39 , nombre: 'Gb-39', chinoTradicional: '懸鐘', nombreTradicional: 'Xuanzhong'  });
const Gb_40 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 40 , nombre: 'Gb-40', chinoTradicional: '丘墟', nombreTradicional: 'Qiuxu'  });
const Gb_41 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 41 , nombre: 'Gb-41', chinoTradicional: '足臨泣', nombreTradicional: 'Zulinqi'  });
const Gb_42 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 42 , nombre: 'Gb-42', chinoTradicional: '地五會', nombreTradicional: 'Diwuhui'  });
const Gb_43 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 43 , nombre: 'Gb-43', chinoTradicional: '俠谿', nombreTradicional: 'Xiaxi'  });
const Gb_44 =  new Punto({canal: 'Canal.SHAOYANG_PIE' , numero: 44 , nombre: 'Gb-44', chinoTradicional: '足竅陰', nombreTradicional: 'Zuqiaoyin'  });




// a este map le pasas {canal, numero} y te devuelve el punto de acupuntura.

var canalNumeroPuntoMap=new Map();
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 1}), SP_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 2}), SP_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 3}), SP_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 4}), SP_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 5}), SP_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 6}), SP_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 7}), SP_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 8}), SP_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 9}), SP_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 10}), SP_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 11}), SP_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 12}), SP_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 13}), SP_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 14}), SP_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 15}), SP_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 16}), SP_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 17}), SP_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 18}), SP_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 19}), SP_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 20}), SP_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_PIE , numero: 21}), SP_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 1}), HT_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 2}), HT_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 3}), HT_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 4}), HT_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 5}), HE_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 6}), HE_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 7}), HE_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 8}), HE_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_MANO , numero: 9}), HE_9 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 1}, Du_1 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 2}, Du_2 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 3}, Du_3 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 4}, Du_4 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 5}, Du_5 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 6}, Du_6 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 7}, Du_7 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 8}, Du_8 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 9}, Du_9 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 10}, Du_10 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 11}, Du_11 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 12}, Du_12 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 13}, Du_13 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 14}, Du_14 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 15}, Du_15 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 16}, Du_16 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 17}, Du_17 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 18}, Du_18 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 19}, Du_19 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 20}, Du_20 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 21}, Du_21 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 22}, Du_22 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 23}, Du_23 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 24}, Du_24 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 25}, Du_25 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 26}, Du_26 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 27}, Du_27 );
canalNumeroPuntoMap.set({canal: Canal.DUMAI , numero: 28}, Du_28 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 1}), St_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 2}), St_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 3}), St_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 4}), St_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 5}), St_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 6}), St_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 7}), St_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 8}), St_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 9}), St_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 10}), St_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 11}), St_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 12}), St_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 13}), St_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 14}), St_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 15}), St_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 16}), St_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 17}), St_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 18}), St_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 19}), St_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 20}), St_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 21}), St_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 22}), St_22 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 23}), St_23 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 24}), St_24 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 25}), St_25 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 26}), St_26 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 27}), St_27 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 28}), St_28 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 29}), St_29 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 30}), St_30 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 31}), St_31 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 32}), St_32 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 33}), St_33 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 34}), St_34 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 35}), St_35 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 36}), St_36 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 37}), St_37 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 38}), St_38 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 39}), St_39 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 40}), St_40 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 41}), St_41 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 42}), St_42 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 43}), St_43 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 44}), St_44 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_PIE , numero: 45}), St_45 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 1}), Liv_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 2}), Liv_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 3}), Liv_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 4}), Liv_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 5}), Liv_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 6}), Liv_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 7}), Liv_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 8}), Liv_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 9}), Liv_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 10}), Liv_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 11}), Liv_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 12}), Liv_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 13}), Liv_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_PIE , numero: 14}), Liv_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 1}), SI_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 2}), SI_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 3}), SI_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 4}), SI_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 5}), SI_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 6}), SI_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 7}), SI_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 8}), SI_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 9}), SI_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 10}), SI_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 11}), SI_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 12}), SI_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 13}), SI_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 14}), SI_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 15}), SI_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 16}), SI_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 17}), SI_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 18}), SI_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_MANO , numero: 19}), SI_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 1}), LI_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 2}), LI_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 3}), LI_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 4}), LI_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 5}), LI_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 6}), LI_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 7}), LI_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 8}), LI_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 9}), LI_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 10}), LI_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 11}), LI_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 12}), LI_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 13}), LI_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 14}), LI_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 15}), LI_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 16}), LI_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 17}), LI_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 18}), LI_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 19}), LI_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.YANGMING_MANO , numero: 20}), LI_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 1}), Pc_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 2}), Pc_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 3}), Pc_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 4}), Pc_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 5}), Pc_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 6}), Pc_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 7}), Pc_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 8}), Pc_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.JUEYIN_MANO , numero: 9}), Pc_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 1}), LU_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 2}), LU_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 3}), LU_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 4}), LU_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 5}), LU_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 6}), LU_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 7}), LU_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 8}), LU_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 9}), LU_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 10}), LU_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYIN_MANO , numero: 11}), LU_11 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 1}, Ren_1 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 2}, Ren_2 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 3}, Ren_3 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 4}, Ren_4 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 5}, Ren_5 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 6}, Ren_6 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 7}, Ren_7 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 8}, Ren_8 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 9}, Ren_9 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 10}, Ren_10 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 11}, Ren_11 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 12}, Ren_12 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 13}, Ren_13 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 14}, Ren_14 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 15}, Ren_15 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 16}, Ren_16 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 17}, Ren_17 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 18}, Ren_18 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 19}, Ren_19 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 20}, Ren_20 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 21}, Ren_21 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 22}, Ren_22 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 23}, Ren_23 );
canalNumeroPuntoMap.set({canal: Canal.RENMAI , numero: 24}, Ren_24 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 1}), Kd_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 2}), Kd_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 3}), Kd_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 4}), Kd_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 5}), Kd_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 6}), Kd_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 7}), Kd_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 8}), Kd_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 9}), Kd_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 10}), Kd_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 11}), Kd_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 12}), Kd_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 13}), Kd_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 14}), Kd_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 15}), Kd_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 16}), Kd_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 17}), Kd_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 18}), Kd_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 19}), Kd_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 20}), Kd_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 21}), Kd_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 22}), Kd_22 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 23}), Kd_23 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 24}), Kd_24 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 25}), Kd_25 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 26}), Kd_26 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYIN_PIE , numero: 27}), Kd_27 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 1}), SJ_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 2}), SJ_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 3}), SJ_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 4}), SJ_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 5}), SJ_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 6}), SJ_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 7}), SJ_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 8}), SJ_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 9}), SJ_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 10}), SJ_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 11}), SJ_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 12}), SJ_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 13}), SJ_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 14}), SJ_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 15}), SJ_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 16}), SJ_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 17}), SJ_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 18}), SJ_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 19}), SJ_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 20}), SJ_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 21}), SJ_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 22}), SJ_22 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_MANO , numero: 23}), SJ_23 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 1}), Bl_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 2}), Bl_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 3}), Bl_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 4}), Bl_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 5}), Bl_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 6}), Bl_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 7}), Bl_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 8}), Bl_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 9}), Bl_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 10}), Bl_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 11}), Bl_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 12}), Bl_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 13}), Bl_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 14}), Bl_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 15}), Bl_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 16}), Bl_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 17}), Bl_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 18}), Bl_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 19}), Bl_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 20}), Bl_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 21}), Bl_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 22}), Bl_22 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 23}), Bl_23 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 24}), Bl_24 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 25}), Bl_25 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 26}), Bl_26 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 27}), Bl_27 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 28}), Bl_28 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 29}), Bl_29 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 30}), Bl_30 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 31}), Bl_31 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 32}), Bl_32 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 33}), Bl_33 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 34}), Bl_34 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 35}), Bl_35 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 36}), Bl_36 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 37}), Bl_37 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 38}), Bl_38 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 39}), Bl_39 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 40}), Bl_40 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 41}), Bl_41 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 42}), Bl_42 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 43}), Bl_43 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 44}), Bl_44 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 45}), Bl_45 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 46}), Bl_46 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 47}), Bl_47 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 48}), Bl_48 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 49}), Bl_49 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 50}), Bl_50 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 51}), Bl_51 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 52}), Bl_52 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 53}), Bl_53 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 54}), Bl_54 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 55}), Bl_55 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 56}), Bl_56 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 57}), Bl_57 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 58}), Bl_58 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 59}), Bl_59 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 60}), Bl_60 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 61}), Bl_61 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 62}), Bl_62 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 63}), Bl_63 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 64}), Bl_64 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 65}), Bl_65 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 66}), Bl_66 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.TAIYANG_PIE , numero: 67}), Bl_67 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 1}), Gb_1 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 2}), Gb_2 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 3}), Gb_3 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 4}), Gb_4 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 5}), Gb_5 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 6}), Gb_6 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 7}), Gb_7 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 8}), Gb_8 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 9}), Gb_9 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 10}), Gb_10 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 11}), Gb_11 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 12}), Gb_12 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 13}), Gb_13 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 14}), Gb_14 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 15}), Gb_15 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 16}), Gb_16 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 17}), Gb_17 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 18}), Gb_18 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 19}), Gb_19 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 20}), Gb_20 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 21}), Gb_21 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 22}), Gb_22 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 23}), Gb_23 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 24}), Gb_24 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 25}), Gb_25 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 26}), Gb_26 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 27}), Gb_27 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 28}), Gb_28 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 29}), Gb_29 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 30}), Gb_30 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 31}), Gb_31 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 32}), Gb_32 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 33}), Gb_33 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 34}), Gb_34 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 35}), Gb_35 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 36}), Gb_36 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 37}), Gb_37 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 38}), Gb_38 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 39}), Gb_39 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 40}), Gb_40 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 41}), Gb_41 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 42}), Gb_42 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 43}), Gb_43 );
canalNumeroPuntoMap.set(JSON.stringify({canal: Canal.SHAOYANG_PIE , numero: 44}), Gb_44 );




module.exports.SP_1 = SP_1;
module.exports.SP_2 = SP_2;
module.exports.SP_3 = SP_3;
module.exports.SP_4 = SP_4;
module.exports.SP_5 = SP_5;
module.exports.SP_6 = SP_6;
module.exports.SP_7 = SP_7;
module.exports.SP_8 = SP_8;
module.exports.SP_9 = SP_9;
module.exports.SP_10 = SP_10;
module.exports.SP_11 = SP_11;
module.exports.SP_12 = SP_12;
module.exports.SP_13 = SP_13;
module.exports.SP_14 = SP_14;
module.exports.SP_15 = SP_15;
module.exports.SP_16 = SP_16;
module.exports.SP_17 = SP_17;
module.exports.SP_18 = SP_18;
module.exports.SP_19 = SP_19;
module.exports.SP_20 = SP_20;
module.exports.SP_21 = SP_21;
module.exports.HT_1 = HT_1;
module.exports.HT_2 = HT_2;
module.exports.HT_3 = HT_3;
module.exports.HT_4 = HT_4;
module.exports.HE_5 = HE_5;
module.exports.HE_6 = HE_6;
module.exports.HE_7 = HE_7;
module.exports.HE_8 = HE_8;
module.exports.HE_9 = HE_9;
module.exports.Du_1 = Du_1;
module.exports.Du_2 = Du_2;
module.exports.Du_3 = Du_3;
module.exports.Du_4 = Du_4;
module.exports.Du_5 = Du_5;
module.exports.Du_6 = Du_6;
module.exports.Du_7 = Du_7;
module.exports.Du_8 = Du_8;
module.exports.Du_9 = Du_9;
module.exports.Du_10 = Du_10;
module.exports.Du_11 = Du_11;
module.exports.Du_12 = Du_12;
module.exports.Du_13 = Du_13;
module.exports.Du_14 = Du_14;
module.exports.Du_15 = Du_15;
module.exports.Du_16 = Du_16;
module.exports.Du_17 = Du_17;
module.exports.Du_18 = Du_18;
module.exports.Du_19 = Du_19;
module.exports.Du_20 = Du_20;
module.exports.Du_21 = Du_21;
module.exports.Du_22 = Du_22;
module.exports.Du_23 = Du_23;
module.exports.Du_24 = Du_24;
module.exports.Du_25 = Du_25;
module.exports.Du_26 = Du_26;
module.exports.Du_27 = Du_27;
module.exports.Du_28 = Du_28;
module.exports.St_1 = St_1;
module.exports.St_2 = St_2;
module.exports.St_3 = St_3;
module.exports.St_4 = St_4;
module.exports.St_5 = St_5;
module.exports.St_6 = St_6;
module.exports.St_7 = St_7;
module.exports.St_8 = St_8;
module.exports.St_9 = St_9;
module.exports.St_10 = St_10;
module.exports.St_11 = St_11;
module.exports.St_12 = St_12;
module.exports.St_13 = St_13;
module.exports.St_14 = St_14;
module.exports.St_15 = St_15;
module.exports.St_16 = St_16;
module.exports.St_17 = St_17;
module.exports.St_18 = St_18;
module.exports.St_19 = St_19;
module.exports.St_20 = St_20;
module.exports.St_21 = St_21;
module.exports.St_22 = St_22;
module.exports.St_23 = St_23;
module.exports.St_24 = St_24;
module.exports.St_25 = St_25;
module.exports.St_26 = St_26;
module.exports.St_27 = St_27;
module.exports.St_28 = St_28;
module.exports.St_29 = St_29;
module.exports.St_30 = St_30;
module.exports.St_31 = St_31;
module.exports.St_32 = St_32;
module.exports.St_33 = St_33;
module.exports.St_34 = St_34;
module.exports.St_35 = St_35;
module.exports.St_36 = St_36;
module.exports.St_37 = St_37;
module.exports.St_38 = St_38;
module.exports.St_39 = St_39;
module.exports.St_40 = St_40;
module.exports.St_41 = St_41;
module.exports.St_42 = St_42;
module.exports.St_43 = St_43;
module.exports.St_44 = St_44;
module.exports.St_45 = St_45;
module.exports.M_LE_8 = M_LE_8;
module.exports.M_UE_1 = M_UE_1;
module.exports.M_UE_9 = M_UE_9;
module.exports.M_HN_3 = M_HN_3;
module.exports.M_BW_35 = M_BW_35;
module.exports.Liv_1 = Liv_1;
module.exports.Liv_2 = Liv_2;
module.exports.Liv_3 = Liv_3;
module.exports.Liv_4 = Liv_4;
module.exports.Liv_5 = Liv_5;
module.exports.Liv_6 = Liv_6;
module.exports.Liv_7 = Liv_7;
module.exports.Liv_8 = Liv_8;
module.exports.Liv_9 = Liv_9;
module.exports.Liv_10 = Liv_10;
module.exports.Liv_11 = Liv_11;
module.exports.Liv_12 = Liv_12;
module.exports.Liv_13 = Liv_13;
module.exports.Liv_14 = Liv_14;
module.exports.SI_1 = SI_1;
module.exports.SI_2 = SI_2;
module.exports.SI_3 = SI_3;
module.exports.SI_4 = SI_4;
module.exports.SI_5 = SI_5;
module.exports.SI_6 = SI_6;
module.exports.SI_7 = SI_7;
module.exports.SI_8 = SI_8;
module.exports.SI_9 = SI_9;
module.exports.SI_10 = SI_10;
module.exports.SI_11 = SI_11;
module.exports.SI_12 = SI_12;
module.exports.SI_13 = SI_13;
module.exports.SI_14 = SI_14;
module.exports.SI_15 = SI_15;
module.exports.SI_16 = SI_16;
module.exports.SI_17 = SI_17;
module.exports.SI_18 = SI_18;
module.exports.SI_19 = SI_19;
module.exports.LI_1 = LI_1;
module.exports.LI_2 = LI_2;
module.exports.LI_3 = LI_3;
module.exports.LI_4 = LI_4;
module.exports.LI_5 = LI_5;
module.exports.LI_6 = LI_6;
module.exports.LI_7 = LI_7;
module.exports.LI_8 = LI_8;
module.exports.LI_9 = LI_9;
module.exports.LI_10 = LI_10;
module.exports.LI_11 = LI_11;
module.exports.LI_12 = LI_12;
module.exports.LI_13 = LI_13;
module.exports.LI_14 = LI_14;
module.exports.LI_15 = LI_15;
module.exports.LI_16 = LI_16;
module.exports.LI_17 = LI_17;
module.exports.LI_18 = LI_18;
module.exports.LI_19 = LI_19;
module.exports.LI_20 = LI_20;
module.exports.Pc_1 = Pc_1;
module.exports.Pc_2 = Pc_2;
module.exports.Pc_3 = Pc_3;
module.exports.Pc_4 = Pc_4;
module.exports.Pc_5 = Pc_5;
module.exports.Pc_6 = Pc_6;
module.exports.Pc_7 = Pc_7;
module.exports.Pc_8 = Pc_8;
module.exports.Pc_9 = Pc_9;
module.exports.LU_1 = LU_1;
module.exports.LU_2 = LU_2;
module.exports.LU_3 = LU_3;
module.exports.LU_4 = LU_4;
module.exports.LU_5 = LU_5;
module.exports.LU_6 = LU_6;
module.exports.LU_7 = LU_7;
module.exports.LU_8 = LU_8;
module.exports.LU_9 = LU_9;
module.exports.LU_10 = LU_10;
module.exports.LU_11 = LU_11;
module.exports.Ren_1 = Ren_1;
module.exports.Ren_2 = Ren_2;
module.exports.Ren_3 = Ren_3;
module.exports.Ren_4 = Ren_4;
module.exports.Ren_5 = Ren_5;
module.exports.Ren_6 = Ren_6;
module.exports.Ren_7 = Ren_7;
module.exports.Ren_8 = Ren_8;
module.exports.Ren_9 = Ren_9;
module.exports.Ren_10 = Ren_10;
module.exports.Ren_11 = Ren_11;
module.exports.Ren_12 = Ren_12;
module.exports.Ren_13 = Ren_13;
module.exports.Ren_14 = Ren_14;
module.exports.Ren_15 = Ren_15;
module.exports.Ren_16 = Ren_16;
module.exports.Ren_17 = Ren_17;
module.exports.Ren_18 = Ren_18;
module.exports.Ren_19 = Ren_19;
module.exports.Ren_20 = Ren_20;
module.exports.Ren_21 = Ren_21;
module.exports.Ren_22 = Ren_22;
module.exports.Ren_23 = Ren_23;
module.exports.Ren_24 = Ren_24;
module.exports.Kd_1 = Kd_1;
module.exports.Kd_2 = Kd_2;
module.exports.Kd_3 = Kd_3;
module.exports.Kd_4 = Kd_4;
module.exports.Kd_5 = Kd_5;
module.exports.Kd_6 = Kd_6;
module.exports.Kd_7 = Kd_7;
module.exports.Kd_8 = Kd_8;
module.exports.Kd_9 = Kd_9;
module.exports.Kd_10 = Kd_10;
module.exports.Kd_11 = Kd_11;
module.exports.Kd_12 = Kd_12;
module.exports.Kd_13 = Kd_13;
module.exports.Kd_14 = Kd_14;
module.exports.Kd_15 = Kd_15;
module.exports.Kd_16 = Kd_16;
module.exports.Kd_17 = Kd_17;
module.exports.Kd_18 = Kd_18;
module.exports.Kd_19 = Kd_19;
module.exports.Kd_20 = Kd_20;
module.exports.Kd_21 = Kd_21;
module.exports.Kd_22 = Kd_22;
module.exports.Kd_23 = Kd_23;
module.exports.Kd_24 = Kd_24;
module.exports.Kd_25 = Kd_25;
module.exports.Kd_26 = Kd_26;
module.exports.Kd_27 = Kd_27;
module.exports.SJ_1 = SJ_1;
module.exports.SJ_2 = SJ_2;
module.exports.SJ_3 = SJ_3;
module.exports.SJ_4 = SJ_4;
module.exports.SJ_5 = SJ_5;
module.exports.SJ_6 = SJ_6;
module.exports.SJ_7 = SJ_7;
module.exports.SJ_8 = SJ_8;
module.exports.SJ_9 = SJ_9;
module.exports.SJ_10 = SJ_10;
module.exports.SJ_11 = SJ_11;
module.exports.SJ_12 = SJ_12;
module.exports.SJ_13 = SJ_13;
module.exports.SJ_14 = SJ_14;
module.exports.SJ_15 = SJ_15;
module.exports.SJ_16 = SJ_16;
module.exports.SJ_17 = SJ_17;
module.exports.SJ_18 = SJ_18;
module.exports.SJ_19 = SJ_19;
module.exports.SJ_20 = SJ_20;
module.exports.SJ_21 = SJ_21;
module.exports.SJ_22 = SJ_22;
module.exports.SJ_23 = SJ_23;
module.exports.Bl_1 = Bl_1;
module.exports.Bl_2 = Bl_2;
module.exports.Bl_3 = Bl_3;
module.exports.Bl_4 = Bl_4;
module.exports.Bl_5 = Bl_5;
module.exports.Bl_6 = Bl_6;
module.exports.Bl_7 = Bl_7;
module.exports.Bl_8 = Bl_8;
module.exports.Bl_9 = Bl_9;
module.exports.Bl_10 = Bl_10;
module.exports.Bl_11 = Bl_11;
module.exports.Bl_12 = Bl_12;
module.exports.Bl_13 = Bl_13;
module.exports.Bl_14 = Bl_14;
module.exports.Bl_15 = Bl_15;
module.exports.Bl_16 = Bl_16;
module.exports.Bl_17 = Bl_17;
module.exports.Bl_18 = Bl_18;
module.exports.Bl_19 = Bl_19;
module.exports.Bl_20 = Bl_20;
module.exports.Bl_21 = Bl_21;
module.exports.Bl_22 = Bl_22;
module.exports.Bl_23 = Bl_23;
module.exports.Bl_24 = Bl_24;
module.exports.Bl_25 = Bl_25;
module.exports.Bl_26 = Bl_26;
module.exports.Bl_27 = Bl_27;
module.exports.Bl_28 = Bl_28;
module.exports.Bl_29 = Bl_29;
module.exports.Bl_30 = Bl_30;
module.exports.Bl_31 = Bl_31;
module.exports.Bl_32 = Bl_32;
module.exports.Bl_33 = Bl_33;
module.exports.Bl_34 = Bl_34;
module.exports.Bl_35 = Bl_35;
module.exports.Bl_36 = Bl_36;
module.exports.Bl_37 = Bl_37;
module.exports.Bl_38 = Bl_38;
module.exports.Bl_39 = Bl_39;
module.exports.Bl_40 = Bl_40;
module.exports.Bl_41 = Bl_41;
module.exports.Bl_42 = Bl_42;
module.exports.Bl_43 = Bl_43;
module.exports.Bl_44 = Bl_44;
module.exports.Bl_45 = Bl_45;
module.exports.Bl_46 = Bl_46;
module.exports.Bl_47 = Bl_47;
module.exports.Bl_48 = Bl_48;
module.exports.Bl_49 = Bl_49;
module.exports.Bl_50 = Bl_50;
module.exports.Bl_51 = Bl_51;
module.exports.Bl_52 = Bl_52;
module.exports.Bl_53 = Bl_53;
module.exports.Bl_54 = Bl_54;
module.exports.Bl_55 = Bl_55;
module.exports.Bl_56 = Bl_56;
module.exports.Bl_57 = Bl_57;
module.exports.Bl_58 = Bl_58;
module.exports.Bl_59 = Bl_59;
module.exports.Bl_60 = Bl_60;
module.exports.Bl_61 = Bl_61;
module.exports.Bl_62 = Bl_62;
module.exports.Bl_63 = Bl_63;
module.exports.Bl_64 = Bl_64;
module.exports.Bl_65 = Bl_65;
module.exports.Bl_66 = Bl_66;
module.exports.Bl_67 = Bl_67;
module.exports.Gb_1 = Gb_1;
module.exports.Gb_2 = Gb_2;
module.exports.Gb_3 = Gb_3;
module.exports.Gb_4 = Gb_4;
module.exports.Gb_5 = Gb_5;
module.exports.Gb_6 = Gb_6;
module.exports.Gb_7 = Gb_7;
module.exports.Gb_8 = Gb_8;
module.exports.Gb_9 = Gb_9;
module.exports.Gb_10 = Gb_10;
module.exports.Gb_11 = Gb_11;
module.exports.Gb_12 = Gb_12;
module.exports.Gb_13 = Gb_13;
module.exports.Gb_14 = Gb_14;
module.exports.Gb_15 = Gb_15;
module.exports.Gb_16 = Gb_16;
module.exports.Gb_17 = Gb_17;
module.exports.Gb_18 = Gb_18;
module.exports.Gb_19 = Gb_19;
module.exports.Gb_20 = Gb_20;
module.exports.Gb_21 = Gb_21;
module.exports.Gb_22 = Gb_22;
module.exports.Gb_23 = Gb_23;
module.exports.Gb_24 = Gb_24;
module.exports.Gb_25 = Gb_25;
module.exports.Gb_26 = Gb_26;
module.exports.Gb_27 = Gb_27;
module.exports.Gb_28 = Gb_28;
module.exports.Gb_29 = Gb_29;
module.exports.Gb_30 = Gb_30;
module.exports.Gb_31 = Gb_31;
module.exports.Gb_32 = Gb_32;
module.exports.Gb_33 = Gb_33;
module.exports.Gb_34 = Gb_34;
module.exports.Gb_35 = Gb_35;
module.exports.Gb_36 = Gb_36;
module.exports.Gb_37 = Gb_37;
module.exports.Gb_38 = Gb_38;
module.exports.Gb_39 = Gb_39;
module.exports.Gb_40 = Gb_40;
module.exports.Gb_41 = Gb_41;
module.exports.Gb_42 = Gb_42;
module.exports.Gb_43 = Gb_43;
module.exports.Gb_44 = Gb_44;

module.exports.canalNumeroPuntoMap=canalNumeroPuntoMap;


// fin de constantes y export de puntos

module.exports.Punto=Punto;
module.exports.puntoPorCanalNumero=puntoPorCanalNumero;